var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.vf||(f.vf=0,f.lg=0);f.vf++;
(function(a){function b(n,r,p){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(w){var v=r;w.total&&(v=w.total);if(w.loaded){t.bf?f.cf[n].loaded=w.loaded:(t.bf=!0,f.cf||(f.cf={}),f.cf[n]={loaded:w.loaded,total:v});var z=v=w=0,C;for(C in f.cf){var G=f.cf[C];w+=G.total;v+=G.loaded;z++}w=Math.ceil(w*f.vf/z);f.setStatus&&f.setStatus("Downloading data... ("+v+"/"+w+")")}else!f.cf&&f.setStatus&&f.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)p(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,v,z){this.start=w;this.end=v;this.audio=z}function r(w){f.lg++;if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);var v=f.getMemory(w.length);f.HEAPU8.set(w,
v);n.prototype.dg=f.HEAPU8.subarray(v,v+w.length);w=a.files;for(v=0;v<w.length;++v)n.prototype.requests[w[v].filename].onload();f.removeRunDependency("datafile_Web_Build/flat-cube.data")}f.FS_createPath("/","Resources",!0,!0);f.FS_createPath("/Resources","Fonts",!0,!0);f.FS_createPath("/Resources","Images",!0,!0);n.prototype={requests:{},open:function(w,v){this.name=v;this.requests[v]=this;f.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.dg.subarray(this.start,this.end))},finish:function(w){var v=
this;f.FS_createPreloadedFile(this.name,null,w,!0,!0,function(){f.removeRunDependency("fp "+v.name)},function(){v.audio?f.removeRunDependency("fp "+v.name):k("Preloading file "+v.name+" failed")},!1,!0);this.requests[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio)).open("GET",p[t].filename);f.addRunDependency("datafile_Web_Build/flat-cube.data");f.Yf||(f.Yf={});f.Yf["Web_Build/flat-cube.data"]={Lg:!1};m?(r(m),m=null):h=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,
window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof f.locateFilePackage||f.locateFile||(f.locateFile=f.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=f.locateFile?f.locateFile("flat-cube.data",""):"flat-cube.data",g=a.remote_package_size,h=null,m=f.getPreloadedPackage?f.getPreloadedPackage(e,g):null;m||b(e,g,function(n){h?(h(n),h=null):m=n},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/Resources/Fonts/gudea.ttf",start:0,end:21196,audio:0},{filename:"/Resources/Images/arrow.png",start:21196,end:22422,audio:0},{filename:"/Resources/Images/icon.png",start:22422,end:26931,audio:0},{filename:"/Resources/Images/scramble.png",
start:26931,end:27858,audio:0},{filename:"/Resources/Images/solve.png",start:27858,end:30637,audio:0},{filename:"/Resources/Images/x.png",start:30637,end:36267,audio:0}],remote_package_size:36267,package_uuid:"e721d2e4-7490-430a-905d-7b5e4511f7af"});var aa={},ba;for(ba in f)f.hasOwnProperty(ba)&&(aa[ba]=f[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,l=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;l="function"===typeof importScripts;
ha=(ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!l;ja=!fa&&!ha&&!l;var ka="",la,ma,na,oa,pa,ra;
if(ha)ka=__dirname+"/",la=function(a,b){pa||(pa=require("fs"));ra||(ra=require("path"));a=ra.normalize(a);return pa.readFileSync(a,b?null:"utf8")},na=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof sa))throw a;}),process.on("unhandledRejection",q),ea=function(a){process.exit(a)},
f.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(la=function(a){return read(a)}),na=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||l)l?ka=self.location.href:document.currentScript&&(ka=document.currentScript.src),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},oa=function(a){document.title=a};var ta=f.print||console.log.bind(console),k=f.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(f[ba]=aa[ba]);aa=null;f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);f.setWindowTitle=oa;function ua(a){va||(va={});va[a]||(va[a]=1,k(a))}var va;
function wa(a,b){b&&b.length?f.dynCall_vi.apply(null,[a].concat(b)):f.dynCall_vi.call(null,a)}var xa=0,za;f.wasmBinary&&(za=f.wasmBinary);var Aa;f.noExitRuntime&&(Aa=f.noExitRuntime);"object"!==typeof WebAssembly&&k("no native wasm support detected");
function Ba(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":Ca[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":y=[b>>>0,(A=b,1<=+Da(A)?0<A?(Ea(+Fa(A/4294967296),4294967295)|0)>>>0:~~+Ga((A-+(~~A>>>0))/4294967296)>>>0:0)];x[a>>2]=y[0];x[a+4>>2]=y[1];break;case "float":B[a>>2]=b;break;case "double":D[a>>3]=b;break;default:q("invalid type for setValue: "+c)}}
var Ha,Ia=new WebAssembly.Table({initial:1075,maximum:1075,element:"anyfunc"}),Ja=!1;function assert(a,b){a||q("Assertion failed: "+b)}function Ka(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=E(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)x[a>>2]=0;for(b=d+c;a<b;)u[a++>>0]=0;return d}a.subarray||a.slice?F.set(a,d):F.set(new Uint8Array(a),d);return d}var La="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&La)return La.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function H(a,b){return a?Ma(F,a,b):""}
function Na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function I(a,b,c){return Na(a,F,b,c)}
function Oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Pa(a){var b=Oa(a)+1,c=Qa(b);Na(a,u,c,b);return c}var buffer,u,F,Ca,Ra,x,Sa,B,D,Ta=f.TOTAL_MEMORY||230686720;f.wasmMemory?Ha=f.wasmMemory:Ha=new WebAssembly.Memory({initial:Ta/65536,maximum:Ta/65536});Ha&&(buffer=Ha.buffer);Ta=buffer.byteLength;
var Ua=buffer;buffer=Ua;f.HEAP8=u=new Int8Array(Ua);f.HEAP16=Ca=new Int16Array(Ua);f.HEAP32=x=new Int32Array(Ua);f.HEAPU8=F=new Uint8Array(Ua);f.HEAPU16=Ra=new Uint16Array(Ua);f.HEAPU32=Sa=new Uint32Array(Ua);f.HEAPF32=B=new Float32Array(Ua);f.HEAPF64=D=new Float64Array(Ua);x[40884]=5406576;function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Nf;"number"===typeof c?void 0===b.lf?f.dynCall_v(c):f.dynCall_vi(c,b.lf):c(void 0===b.lf?null:b.lf)}}}
var Wa=[],Xa=[],Ya=[],Za=[],$a=[],ab=!1;function bb(){var a=f.preRun.shift();Wa.unshift(a)}var Da=Math.abs,Ga=Math.ceil,Fa=Math.floor,Ea=Math.min,cb=0,db=null,eb=null;function fb(){cb++;f.monitorRunDependencies&&f.monitorRunDependencies(cb)}function gb(){cb--;f.monitorRunDependencies&&f.monitorRunDependencies(cb);if(0==cb&&(null!==db&&(clearInterval(db),db=null),eb)){var a=eb;eb=null;a()}}f.preloadedImages={};f.preloadedAudios={};
function q(a){if(f.onAbort)f.onAbort(a);ta(a);k(a);Ja=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function hb(){var a=ib;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var ib="flat-cube.wasm";if(!hb()){var jb=ib;ib=f.locateFile?f.locateFile(jb,ka):ka+jb}
function kb(){try{if(za)return new Uint8Array(za);if(na)return na(ib);throw"both async and sync fetching of the wasm failed";}catch(a){q(a)}}function lb(){return za||!fa&&!l||"function"!==typeof fetch?new Promise(function(a){a(kb())}):fetch(ib,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+ib+"'";return a.arrayBuffer()}).catch(function(){return kb()})}
var A,y,nb={95674:function(a){a=H(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ka(mb(a))},128500:function(a,b,c){f.SDL2||(f.SDL2={});var d=f.SDL2;d.eg!==f.canvas&&(d.Te=f.createContext(f.canvas,!1,!0),d.eg=f.canvas);if(d.Cg!==a||d.mg!==b||d.og!==d.Te)d.image=d.Te.createImageData(a,b),d.Cg=a,d.mg=b,d.og=d.Te;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=x[b];a[e]=
g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.Jg!==a&&(d.fg=new Int32Array(a.buffer),d.gg=new Uint8Array(a.buffer)),a=d.fg,c=a.length,a.set(x.subarray(b,b+c)),a=d.gg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Te.putImageData(d.image,0,0);return 0},129955:function(a,b,c,d,e){var g=document.createElement("canvas");g.width=
a;g.height=b;var h=g.getContext("2d");a=h.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=x[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(x.subarray(e,e+n));h.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=E(c.length+1);I(c,d,c.length+1);return d},130944:function(a){f.canvas&&
(f.canvas.style.cursor=H(a));return 0},131037:function(){f.canvas&&(f.canvas.style.cursor="none")},132262:function(){return screen.width},132289:function(){return screen.height},132362:function(a){"undefined"!==typeof f.setWindowTitle&&f.setWindowTitle(H(a));return 0},132516:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},132682:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==
typeof navigator.webkitGetUserMedia?1:0},132908:function(a){"undefined"===typeof f.SDL2&&(f.SDL2={});var b=f.SDL2;a?b.capture={}:b.audio={};b.Me||("undefined"!==typeof AudioContext?b.Me=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Me=new webkitAudioContext));return void 0===b.Me?-1:0},133391:function(){return f.SDL2.Me.sampleRate},133461:function(a,b,c,d){function e(){}function g(m){void 0!==h.capture.kf&&(clearTimeout(h.capture.kf),h.capture.kf=void 0);h.capture.pf=h.Me.createMediaStreamSource(m);
h.capture.Oe=h.Me.createScriptProcessor(b,a,1);h.capture.Oe.onaudioprocess=function(n){void 0!==h&&void 0!==h.capture&&(n.outputBuffer.getChannelData(0).fill(0),h.capture.uf=n.inputBuffer,wa(c,[d]))};h.capture.pf.connect(h.capture.Oe);h.capture.Oe.connect(h.Me.destination);h.capture.stream=m}var h=f.SDL2;h.capture.sf=h.Me.createBuffer(a,b,h.Me.sampleRate);h.capture.sf.getChannelData(0).fill(0);h.capture.kf=setTimeout(function(){h.capture.uf=h.capture.sf;wa(c,[d])},b/h.Me.sampleRate*1E3);void 0!==
navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},135113:function(a,b,c,d){var e=f.SDL2;e.audio.Oe=e.Me.createScriptProcessor(b,0,a);e.audio.Oe.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.Kf=g.outputBuffer,wa(c,[d]))};e.audio.Oe.connect(e.Me.destination)},135523:function(a,b){for(var c=f.SDL2,
d=c.capture.uf.numberOfChannels,e=0;e<d;++e){var g=c.capture.uf.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var h=0;h<b;++h)Ba(a+4*h,g[h]);else for(h=0;h<b;++h)Ba(a+4*(h*d+e),g[h])}},136128:function(a,b){for(var c=f.SDL2,d=c.audio.Kf.numberOfChannels,e=0;e<d;++e){var g=c.audio.Kf.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+
" samples vs expected "+b+" samples!";for(var h=0;h<b;++h)g[h]=B[a+(h*d+e<<2)>>2]}},136608:function(a){var b=f.SDL2;if(a){void 0!==b.capture.kf&&clearTimeout(b.capture.kf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.Oe&&(b.capture.Oe.onaudioprocess=function(){},b.capture.Oe.disconnect(),b.capture.Oe=void 0);void 0!==b.capture.pf&&(b.capture.pf.disconnect(),b.capture.pf=void 0);
void 0!==b.capture.sf&&(b.capture.sf=void 0);b.capture=void 0}else void 0!=b.audio.Oe&&(b.audio.Oe.disconnect(),b.audio.Oe=void 0),b.audio=void 0;void 0!==b.Me&&void 0===b.audio&&void 0===b.capture&&(b.Me.close(),b.Me=void 0)}};Xa.push({Nf:function(){ob()}});
function pb(a,b){qb=a;rb=b;if(sb)if(0==a)tb=function(){var d=Math.max(0,ub+b-vb())|0;setTimeout(wb,d)};else if(1==a)tb=function(){xb(wb)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);l?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}tb=function(){setImmediate(wb)}}}function vb(){q()}
function yb(a,b,c,d,e){Aa=!0;assert(!sb,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");sb=a;zb=d;var g="undefined"!==typeof d?function(){f.dynCall_vi(a,d)}:function(){f.dynCall_v(a)};var h=Ab;wb=function(){if(!Ja)if(0<Bb.length){var m=Date.now(),n=Bb.shift();n.Nf(n.lf);if(Cb){var r=Cb,p=0==r%1?r-1:Math.floor(r);Cb=n.Ig?p:(8*r+(p+.5))/9}console.log('main loop blocker "'+
n.name+'" took '+(Date.now()-m)+" ms");f.setStatus&&(m=f.statusMessage||"Please wait...",n=Cb,r=Db.Kg,n?n<r?f.setStatus(m+" ("+(r-n)+"/"+r+")"):f.setStatus(m):f.setStatus(""));h<Ab||setTimeout(wb,0)}else if(!(h<Ab))if(Eb=Eb+1|0,1==qb&&1<rb&&0!=Eb%rb)tb();else{0==qb&&(ub=vb());a:if(!(Ja||f.preMainLoop&&!1===f.preMainLoop())){try{g()}catch(t){if(t instanceof sa)break a;t&&"object"===typeof t&&t.stack&&k("exception thrown: "+[t,t.stack]);throw t;}f.postMainLoop&&f.postMainLoop()}h<Ab||("object"===typeof SDL&&
SDL.audio&&SDL.audio.vg&&SDL.audio.vg(),tb())}};e||(b&&0<b?pb(0,1E3/b):pb(1,1),tb());if(c)throw"unwind";}var tb=null,Ab=0,sb=null,zb=0,qb=0,rb=0,Eb=0,Bb=[],Db={},ub,wb,Cb,Fb=!1,Gb=!1,Hb=[];
function Ib(){function a(){Gb=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Jb){Jb=!0;try{Kb=!0}catch(c){Kb=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Lb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Kb?null:console.log("warning: no BlobBuilder");
Mb="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Wf||"undefined"!==typeof Mb||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Wf=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Wf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var h=null;if(Kb)try{h=new Blob([c],{type:Nb(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Nb(d)}))}catch(r){ua("Blob constructor present but fails: "+
r+"; falling back to blob builder")}h||(h=new Lb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var m=Mb.createObjectURL(h),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);f.preloadedImages[d]=r;Mb.revokeObjectURL(m);e&&e(c)};n.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Rg&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function h(t){n||(n=!0,f.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,f.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(Kb){try{var r=new Blob([c],{type:Nb(d)})}catch(t){return m()}r=Mb.createObjectURL(r);var p=new Audio;p.addEventListener("canplaythrough",function(){h(p)},!1);p.onerror=function(){if(!n){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",w=0,v=0,
z=0;z<c.length;z++)for(w=w<<8|c[z],v+=8;6<=v;){var C=w>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[C]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;h(p)}};p.src=r;Ob(function(){h(p)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&
b.addEventListener("click",function(c){!Gb&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Pb(a,b,c,d){if(b&&f.Te&&a==f.canvas)return f.Te;var e;if(b){var g={antialias:!1,alpha:!1,Sf:1};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof Qb&&(e=Rb(a,g)))var m=J[e].Xe}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof K,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Te=m,b&&Sb(e),f.Bg=b,Hb.forEach(function(n){n()}),Ib());return m}var Tb=!1,Ub=void 0,Vb=void 0;
function Wb(a,b,c){function d(){Fb=!1;var h=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(e.exitFullscreen=Xb,Ub&&e.requestPointerLock(),Fb=!0,Vb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=Sa[SDL.screen>>2]|8388608),Yb(f.canvas),Zb()):Yb(e)):(h.parentNode.insertBefore(e,h),h.parentNode.removeChild(h),Vb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=Sa[SDL.screen>>
2]&-8388609),Yb(f.canvas),Zb()):Yb(e));if(f.onFullScreen)f.onFullScreen(Fb);if(f.onFullscreen)f.onFullscreen(Fb)}Ub=a;Vb=b;$b=c;"undefined"===typeof Ub&&(Ub=!0);"undefined"===typeof Vb&&(Vb=!1);"undefined"===typeof $b&&($b=null);var e=f.canvas;Tb||(Tb=!0,document.addEventListener("fullscreenchange",d,!1),document.addEventListener("mozfullscreenchange",d,!1),document.addEventListener("webkitfullscreenchange",d,!1),document.addEventListener("MSFullscreenChange",d,!1));var g=document.createElement("div");
e.parentNode.insertBefore(g,e);g.appendChild(e);g.requestFullscreen=g.requestFullscreen||g.mozRequestFullScreen||g.msRequestFullscreen||(g.webkitRequestFullscreen?function(){g.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(g.webkitRequestFullScreen?function(){g.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);c?g.requestFullscreen({Ug:c}):g.requestFullscreen()}
function Xb(){if(!Fb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var ac=0;function xb(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ac)ac=b+1E3/60;else for(;b+2>=ac;)ac+=1E3/60;setTimeout(a,Math.max(ac-b,0))}}function Ob(a){Aa=!0;setTimeout(function(){Ja||a()},1E4)}
function Nb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}function bc(a,b,c){var d="al "+a;ma(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&gb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&fb(d)}var cc=[];function Zb(){var a=f.canvas;cc.forEach(function(b){b(a.width,a.height)})}
function Yb(a,b,c){b&&c?(a.Dg=b,a.ng=c):(b=a.Dg,c=a.ng);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Vb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Jb,Kb,Lb,Mb,$b;
function dc(a){f.___errno_location&&(x[f.___errno_location()>>2]=a)}function ec(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function fc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ec(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ic(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jc(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ec(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kc=[];function lc(a,b){kc[a]={input:[],output:[],ef:b};mc(a,nc)}
var nc={open:function(a){var b=kc[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ef.flush(a.tty)},flush:function(a){a.tty.ef.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ef.Of)throw new M(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ef.Of(a.tty)}catch(m){throw new M(29);}if(void 0===h&&0===e)throw new M(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ef.Af)throw new M(60);
try{for(var e=0;e<d;e++)a.tty.ef.Af(a.tty,b[c+e])}catch(g){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},oc={Of:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.bf?Buffer.bf(256):new Buffer(256),d=0;try{d=pa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},Af:function(a,b){null===b||10===b?(ta(Ma(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ta(Ma(a.output,0)),a.output=[])}},pc={Af:function(a,b){null===b||10===b?(k(Ma(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ma(a.output,0)),a.output=[])}},N={Ve:null,We:function(){return N.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.Ve||(N.Ve={dir:{node:{Ze:N.Je.Ze,Pe:N.Je.Pe,lookup:N.Je.lookup,qf:N.Je.qf,rename:N.Je.rename,unlink:N.Je.unlink,rmdir:N.Je.rmdir,readdir:N.Je.readdir,symlink:N.Je.symlink},stream:{af:N.Ke.af}},file:{node:{Ze:N.Je.Ze,Pe:N.Je.Pe},stream:{af:N.Ke.af,read:N.Ke.read,write:N.Ke.write,Ef:N.Ke.Ef,Tf:N.Ke.Tf,Vf:N.Ke.Vf}},link:{node:{Ze:N.Je.Ze,Pe:N.Je.Pe,readlink:N.Je.readlink},stream:{}},Jf:{node:{Ze:N.Je.Ze,
Pe:N.Je.Pe},stream:qc}});c=rc(a,b,c,d);16384===(c.mode&61440)?(c.Je=N.Ve.dir.node,c.Ke=N.Ve.dir.stream,c.Ie={}):32768===(c.mode&61440)?(c.Je=N.Ve.file.node,c.Ke=N.Ve.file.stream,c.Le=0,c.Ie=null):40960===(c.mode&61440)?(c.Je=N.Ve.link.node,c.Ke=N.Ve.link.stream):8192===(c.mode&61440)&&(c.Je=N.Ve.Jf.node,c.Ke=N.Ve.Jf.stream);c.timestamp=Date.now();a&&(a.Ie[b]=c);return c},Mg:function(a){if(a.Ie&&a.Ie.subarray){for(var b=[],c=0;c<a.Le;++c)b.push(a.Ie[c]);return b}return a.Ie},Ng:function(a){return a.Ie?
a.Ie.subarray?a.Ie.subarray(0,a.Le):new Uint8Array(a.Ie):new Uint8Array},Lf:function(a,b){var c=a.Ie?a.Ie.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Ie,a.Ie=new Uint8Array(b),0<a.Le&&a.Ie.set(c.subarray(0,a.Le),0))},wg:function(a,b){if(a.Le!=b)if(0==b)a.Ie=null,a.Le=0;else{if(!a.Ie||a.Ie.subarray){var c=a.Ie;a.Ie=new Uint8Array(new ArrayBuffer(b));c&&a.Ie.set(c.subarray(0,Math.min(b,a.Le)))}else if(a.Ie||(a.Ie=[]),a.Ie.length>b)a.Ie.length=b;else for(;a.Ie.length<
b;)a.Ie.push(0);a.Le=b}},Je:{Ze:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Le:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.cg=4096;b.blocks=Math.ceil(b.size/b.cg);return b},Pe:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=
b.timestamp);void 0!==b.size&&N.wg(a,b.size)},lookup:function(){throw sc[44];},qf:function(a,b,c,d){return N.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tc(b,c)}catch(g){}if(d)for(var e in d.Ie)throw new M(55);}delete a.parent.Ie[a.name];a.name=c;b.Ie[c]=a;a.parent=b},unlink:function(a,b){delete a.Ie[b]},rmdir:function(a,b){var c=tc(a,b),d;for(d in c.Ie)throw new M(55);delete a.Ie[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Ie)a.Ie.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Ke:{read:function(a,b,c,d,e){var g=a.node.Ie;if(e>=a.node.Le)return 0;a=Math.min(a.node.Le-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ie||a.Ie.subarray)){if(g)return a.Ie=b.subarray(c,
c+d),a.Le=d;if(0===a.Le&&0===e)return a.Ie=new Uint8Array(b.subarray(c,c+d)),a.Le=d;if(e+d<=a.Le)return a.Ie.set(b.subarray(c,c+d),e),d}N.Lf(a,e+d);if(a.Ie.subarray&&b.subarray)a.Ie.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.Ie[e+g]=b[c+g];a.Le=Math.max(a.Le,e+d);return d},af:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Le);if(0>b)throw new M(28);return b},Ef:function(a,b,c){N.Lf(a.node,b+c);a.node.Le=Math.max(a.node.Le,b+c)},Tf:function(a,b,c,d,e,g,h){if(32768!==
(a.node.mode&61440))throw new M(43);c=a.node.Ie;if(h&2||c.buffer!==b.buffer){if(0<e||e+d<a.node.Le)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==u.buffer;d=E(d);if(!d)throw new M(48);(e?u:b).set(c,d)}else a=!1,d=c.byteOffset;return{Tg:d,Gg:a}},Vf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);if(e&2)return 0;N.Ke.write(a,b,0,d,c,!1);return 0}}},uc=null,vc={},wc=[],xc=1,yc=null,zc=!0,Ac={},M=null,sc={};
function Bc(a,b){a=jc("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Mf:!0,Bf:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Bf)throw new M(32);a=ec(a.split("/").filter(function(h){return!!h}),!1);var e=uc;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=tc(e,a[d]);c=fc(c+"/"+a[d]);e.jf&&(!g||g&&b.Mf)&&(e=e.jf.root);if(!g||b.wf)for(g=0;40960===(e.mode&61440);)if(e=Dc(c),c=jc(hc(c),e),e=Bc(c,{Bf:b.Bf}).node,40<g++)throw new M(32);}return{path:c,node:e}}
function Ec(a){for(var b;;){if(a===a.parent)return a=a.We.Uf,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yc.length}function Gc(a){var b=Fc(a.parent.id,a.name);a.df=yc[b];yc[b]=a}function tc(a,b){var c;if(c=(c=Hc(a,"x"))?c:a.Je.lookup?0:2)throw new M(c,a);for(c=yc[Fc(a.id,b)];c;c=c.df){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Je.lookup(a,b)}
function rc(a,b,c,d){Ic||(Ic=function(e,g,h,m){e||(e=this);this.parent=e;this.We=e.We;this.jf=null;this.id=xc++;this.name=g;this.mode=h;this.Je={};this.Ke={};this.rdev=m},Ic.prototype={},Object.defineProperties(Ic.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(e){e?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(e){e?this.mode|=146:this.mode&=-147}},sg:{get:function(){return 16384===(this.mode&61440)}},rg:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Ic(a,b,c,d);Gc(a);return a}var Jc={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Kc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hc(a,b){if(zc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lc(a,b){try{return tc(a,b),20}catch(c){}return Hc(a,"wx")}
function Mc(a){var b=4096;for(a=a||0;a<=b;a++)if(!wc[a])return a;throw new M(33);}function Nc(a,b){Oc||(Oc=function(){},Oc.prototype={},Object.defineProperties(Oc.prototype,{object:{get:function(){return this.node},set:function(e){this.node=e}}}));var c=new Oc,d;for(d in a)c[d]=a[d];a=c;b=Mc(b);a.fd=b;return wc[b]=a}var qc={open:function(a){a.Ke=vc[a.node.rdev].Ke;a.Ke.open&&a.Ke.open(a)},af:function(){throw new M(70);}};function mc(a,b){vc[a]={Ke:b}}
function Pc(a,b){var c="/"===b,d=!b;if(c&&uc)throw new M(10);if(!c&&!d){var e=Bc(b,{Mf:!1});b=e.path;e=e.node;if(e.jf)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,Sg:{},Uf:b,tg:[]};a=a.We(b);a.We=b;b.root=a;c?uc=a:e&&(e.jf=b,e.We&&e.We.tg.push(b))}function Qc(a,b,c){var d=Bc(a,{parent:!0}).node;a=ic(a);if(!a||"."===a||".."===a)throw new M(28);var e=Lc(d,a);if(e)throw new M(e);if(!d.Je.qf)throw new M(63);return d.Je.qf(d,a,b,c)}
function O(a,b){return Qc(a,(void 0!==b?b:511)&1023|16384,0)}function Rc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Qc(a,b|8192,c)}function Sc(a,b){if(!jc(a))throw new M(44);var c=Bc(b,{parent:!0}).node;if(!c)throw new M(44);b=ic(b);var d=Lc(c,b);if(d)throw new M(d);if(!c.Je.symlink)throw new M(63);return c.Je.symlink(c,b,a)}
function Tc(a){var b=Bc(a,{parent:!0}).node,c=ic(a),d=tc(b,c);a:{try{var e=tc(b,c)}catch(h){e=h.Ye;break a}var g=Hc(b,"wx");e=g?g:16384===(e.mode&61440)?31:0}if(e)throw new M(e);if(!b.Je.unlink)throw new M(63);if(d.jf)throw new M(10);try{Ac.willDeletePath&&Ac.willDeletePath(a)}catch(h){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Je.unlink(b,c);b=Fc(d.parent.id,d.name);if(yc[b]===d)yc[b]=d.df;else for(b=yc[b];b;){if(b.df===d){b.df=d.df;break}b=b.df}try{if(Ac.onDeletePath)Ac.onDeletePath(a)}catch(h){k("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Dc(a){a=Bc(a).node;if(!a)throw new M(44);if(!a.Je.readlink)throw new M(28);return jc(Ec(a.parent),a.Je.readlink(a))}function Uc(a,b){var c;"string"===typeof a?c=Bc(a,{wf:!0}).node:c=a;if(!c.Je.Pe)throw new M(63);c.Je.Pe(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Vc(a,b,c,d){if(""===a)throw new M(44);if("string"===typeof b){var e=Jc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=fc(a);try{g=Bc(a,{wf:!(b&131072)}).node}catch(m){}}e=!1;if(b&64)if(g){if(b&128)throw new M(20);}else g=Qc(a,c,0),e=!0;if(!g)throw new M(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new M(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Kc(b)||b&512)?31:Hc(g,Kc(b)):44))throw new M(c);if(b&512){c=g;var h;"string"===typeof c?h=Bc(c,{wf:!0}).node:h=c;if(!h.Je.Pe)throw new M(63);if(16384===(h.mode&61440))throw new M(31);if(32768!==(h.mode&61440))throw new M(28);if(c=Hc(h,"w"))throw new M(c);h.Je.Pe(h,{size:0,timestamp:Date.now()})}b&=-641;d=Nc({node:g,path:Ec(g),flags:b,seekable:!0,position:0,Ke:g.Ke,Ag:[],error:!1},d);d.Ke.open&&d.Ke.open(d);!f.logReadFiles||b&1||(Wc||(Wc={}),a in Wc||(Wc[a]=1,k("FS.trackingDelegate error on read file: "+
a)));try{Ac.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),Ac.onOpenFile(a,g))}catch(m){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}function Xc(a){if(null===a.fd)throw new M(8);a.xf&&(a.xf=null);try{a.Ke.close&&a.Ke.close(a)}catch(b){throw b;}finally{wc[a.fd]=null}a.fd=null}
function Yc(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.Ke.af)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Ke.af(a,b,c);a.Ag=[]}
function Zc(a,b,c,d,e,g){if(0>d||0>e)throw new M(28);if(null===a.fd)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.Ke.write)throw new M(28);a.flags&1024&&Yc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new M(70);b=a.Ke.write(a,b,c,d,e,g);h||(a.position+=b);try{if(a.path&&Ac.onWriteToFile)Ac.onWriteToFile(a.path)}catch(m){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b}
function $c(){M||(M=function(a,b){this.node=b;this.yg=function(c){this.Ye=c};this.yg(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(function(a){sc[a]=new M(a);sc[a].stack="<generic error, no stack>"}))}var ad;function bd(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function cd(a,b,c,d){a=fc(("string"===typeof a?a:Ec(a))+"/"+b);return O(a,bd(c,d))}
function dd(a,b){a="string"===typeof a?a:Ec(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fc(a+"/"+c);try{O(d)}catch(e){}a=d}}return d}function ed(a,b,c,d){a=fc(("string"===typeof a?a:Ec(a))+"/"+b);c=bd(c,d);return Qc(a,(void 0!==c?c:438)&4095|32768,0)}
function fd(a,b,c,d,e,g){a=b?fc(("string"===typeof a?a:Ec(a))+"/"+b):a;d=bd(d,e);e=Qc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Uc(e,d|146);a=Vc(e,"w");Zc(a,c,0,c.length,0,g);Xc(a);Uc(e,d)}return e}
function gd(a,b,c,d){a=fc(("string"===typeof a?a:Ec(a))+"/"+b);b=bd(!!c,!!d);gd.Rf||(gd.Rf=64);var e=gd.Rf++<<8|0;mc(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,m,n){for(var r=0,p=0;p<n;p++){try{var t=c()}catch(w){throw new M(29);}if(void 0===t&&0===r)throw new M(6);if(null===t||void 0===t)break;r++;h[m+p]=t}r&&(g.node.timestamp=Date.now());return r},write:function(g,h,m,n){for(var r=0;r<n;r++)try{d(h[m+r])}catch(p){throw new M(29);}n&&
(g.node.timestamp=Date.now());return r}});return Rc(a,b,e)}function hd(a,b,c){a=fc(("string"===typeof a?a:Ec(a))+"/"+b);return Sc(c,a)}
function id(a){if(a.rg||a.sg||a.link||a.Ie)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.Ie=mb(la(a.url),!0),a.Le=a.Ie.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||dc(29);return b}
function jd(a,b,c,d,e){function g(){this.yf=!1;this.nf=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.Pf(p/this.chunkSize|0)[t]}};g.prototype.xg=function(p){this.Pf=p};g.prototype.Gf=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),w,v=(w=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;p=(w=p.getResponseHeader("Content-Encoding"))&&"gzip"===w;var z=1048576;v||(z=t);var C=this;C.xg(function(G){var ya=G*z,qa=(G+1)*z-1;qa=Math.min(qa,t-1);if("undefined"===typeof C.nf[G]){var Cc=C.nf;if(ya>qa)throw Error("invalid range ("+ya+", "+qa+") or no bytes requested!");if(qa>t-1)throw Error("only "+t+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);t!==z&&L.setRequestHeader("Range","bytes="+ya+"-"+qa);"undefined"!=typeof Uint8Array&&(L.responseType=
"arraybuffer");L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);ya=void 0!==L.response?new Uint8Array(L.response||[]):mb(L.responseText||"",!0);Cc[G]=ya}if("undefined"===typeof C.nf[G])throw Error("doXHR failed!");return C.nf[G]});if(p||!t)z=t=1,z=t=this.Pf(0).length,ta("LazyFiles on gzip forces download of the whole file when length is accessed");this.bg=
t;this.ag=z;this.yf=!0};if("undefined"!==typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.yf||this.Gf();return this.bg}},chunkSize:{get:function(){this.yf||this.Gf();return this.ag}}});var m=void 0}else m=c,h=void 0;var n=ed(a,b,d,e);h?n.Ie=h:m&&(n.Ie=null,n.url=m);Object.defineProperties(n,{Le:{get:function(){return this.Ie.length}}});
var r={};Object.keys(n.Ke).forEach(function(p){var t=n.Ke[p];r[p]=function(){if(!id(n))throw new M(29);return t.apply(null,arguments)}});r.read=function(p,t,w,v,z){if(!id(n))throw new M(29);p=p.node.Ie;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var C=0;C<v;C++)t[w+C]=p[z+C];else for(C=0;C<v;C++)t[w+C]=p.get(z+C);return v};n.Ke=r;return n}
function kd(a,b,c,d,e,g,h,m,n,r){function p(v){function z(G){r&&r();m||fd(a,b,G,d,e,n);g&&g();gb(w)}var C=!1;f.preloadPlugins.forEach(function(G){!C&&G.canHandle(t)&&(G.handle(v,t,z,function(){h&&h();gb(w)}),C=!0)});C||z(v)}Ib();var t=b?jc(fc(a+"/"+b)):a,w="cp "+t;fb(w);"string"==typeof c?bc(c,function(v){p(v)},h):p(c)}var ld={},Ic,Oc,Wc,md=0;function P(){md+=4;return x[md-4>>2]}function nd(a){void 0===a&&(a=P());a=wc[a];if(!a)throw new M(8);return a}var od=ha||"undefined"!==typeof dateNow||1;
function pd(){q("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")}var Q=12288,qd=!1,rd=0,sd=0,td=0,R={alpha:!1,depth:!1,stencil:!1,antialias:!1},ud={},vd;
function wd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,h){b.drawElementsInstancedANGLE(c,d,e,g,h)})}
function xd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function yd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var zd=1,Ad=0,Bd=[],S=[],Cd=[],Dd=[],Ed=[],T=[],U=[],Fd=[],J={},Gd=null,V=[],Hd={},Id={},Jd=4;function W(a){Ad||(Ad=a)}function Kd(a){for(var b=zd++,c=a.length;c<b;c++)a[c]=null;return b}var Ld=[0],Md=[0];function Rb(a,b){if(a=a.getContext("webgl",b)){var c=E(8),d={Og:c,attributes:b,version:b.Sf,Xe:a};a.canvas&&(a.canvas.ff=d);J[c]=d;("undefined"===typeof b.ig||b.ig)&&Nd(d);b=c}else b=0;return b}function Sb(a){Gd=J[a];f.Te=K=Gd&&Gd.Xe}
function Nd(a){a||(a=Gd);if(!a.pg){a.pg=!0;var b=a.Xe;2>a.version&&(wd(b),xd(b),yd(b));b.Qe=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Qb={},Od,Pd;function Qd(){Q=12288;return 1}var Rd=0,Sd=0,Td=0,Ud=0,Vd=0,Wd=0,Xd=0,Yd=0,Zd=0,$d=null,ae=null,be=null,ce=!1;function de(){for(var a=ee.length-1;0<=a;--a)fe(a);ee=[];X=[]}var X=[];
function ge(a,b,c){function d(h,m){if(h.length!=m.length)return!1;for(var n in h)if(h[n]!=m[n])return!1;return!0}for(var e in X){var g=X[e];if(g.Df==a&&d(g.Ff,c))return}X.push({Df:a,Xf:b,Ff:c});X.sort(function(h,m){return h.Xf<m.Xf})}function he(a){for(var b=0;b<X.length;++b)X[b].Df==a&&(X.splice(b,1),--b)}function ie(){if(je&&ke.$e)for(var a=0;a<X.length;++a){var b=X[a];X.splice(a,1);--a;b.Df.apply(this,b.Ff)}}var je=0,ke=null,ee=[];
function fe(a){var b=ee[a];b.target.removeEventListener(b.Ne,b.jg,b.Re);ee.splice(a,1)}function le(a){function b(d){++je;ke=a;ie();a.Ue(d);ie();--je}if(a.Se)a.jg=b,a.target.addEventListener(a.Ne,b,a.Re),ee.push(a),ce||(Za.push(de),ce=!0);else for(var c=0;c<ee.length;++c)ee[c].target==a.target&&ee[c].Ne==a.Ne&&fe(c--)}function me(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function ne(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var oe={},pe,qe,re={};function se(a){return a===a+0?H(a):a}var te=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Y(a){return te[a]||("undefined"!==typeof document?document.querySelector(se(a)):void 0)}function ue(a){var b=ve(),c=Qa(8),d=c+4,e=Qa(a.id.length+1);I(a.id,e,a.id.length+1);if(a=Y(e))x[c>>2]=a.width,x[d>>2]=a.height;c=[x[c>>2],x[d>>2]];we(b);return c}function xe(a,b,c){a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function ye(a,b,c){if(a.Hg){var d=ve(),e=Qa(a.id.length+1);I(a.id,e,a.id.length+1);xe(e,b,c);we(d)}else a.width=b,a.height=c}
function ze(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ye(a,d,e),a.style.width=g,a.style.height=h,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=w,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=C,a.style.marginBottom=G,document.body.style.margin=ya,document.documentElement.style.overflow=qa,document.body.scroll=Cc,a.style.Qf=L,a.ff&&a.ff.Xe.viewport(0,0,d,e),re.mf&&Z(re.mf,37,0,re.Hf))}var c=ue(a),d=c[0],e=c[1],g=a.style.width,h=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,w=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,C=a.style.marginTop,G=a.style.marginBottom,
ya=document.body.style.margin,qa=document.documentElement.style.overflow,Cc=document.body.scroll,L=a.style.Qf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Ae(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}
function Be(a,b){if(0!=b.Cf||0!=b.tf){ze(a);var c=b.zg?innerWidth:screen.width,d=b.zg?innerHeight:screen.height,e=a.getBoundingClientRect(),g=e.width;e=e.height;var h=ue(a),m=h[0];h=h[1];3==b.Cf?(Ae(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.Cf&&(c*h<m*d?(g=h*c/m,Ae(a,(d-g)/2,0),d=g):(g=m*d/h,Ae(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.kg&&(a.style.Qf=
"pixelated");g=2==b.tf?devicePixelRatio:1;0!=b.tf&&(c=c*g|0,d=d*g|0,ye(a,c,d),a.ff&&a.ff.Xe.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ne()?-3:-1;b.mf&&Z(b.mf,37,0,b.Hf);return 0}function Ce(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.rf)a.rf();else return document.body.requestPointerLock||document.body.rf?-3:-1;return 0}
function De(a,b){D[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)D[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)D[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;I(b.id,a+1304,64);I(b.mapping,a+1368,64)}var Ee=[];
function Fe(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),h=g&&Kd(d);g?(g.name=h,d[h]=g):W(1282);x[b+4*e>>2]=h}}
function Ge(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&W(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":W(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:W(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:B[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){W(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:W(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:y=
[d>>>0,(A=d,1<=+Da(A)?0<A?(Ea(+Fa(A/4294967296),4294967295)|0)>>>0:~~+Ga((A-+(~~A>>>0))/4294967296)>>>0:0)];x[b>>2]=y[0];x[b+4>>2]=y[1];break;case 0:x[b>>2]=d;break;case 2:B[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else W(1281)}function He(a){var b=Oa(a)+1,c=E(b);I(a,c,b);return c}
function Ie(a,b,c,d){if(c)if(a=K.getUniform(S[a],T[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:B[c>>2]=a;break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;default:throw"internal emscriptenWebGLGetUniform() error, bad type: "+d;}else W(1281)}
function Je(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)x[c>>2]=a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:B[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+d;}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:B[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b]);break;default:throw"internal emscriptenWebGLGetVertexAttrib() error, bad type: "+
d;}else W(1281)}function Ke(a,b,c,d,e){a-=5120;a=1==a?F:4==a?x:6==a?B:5==a||28922==a?Sa:Ra;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Jd;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var Le=0;
function Me(a,b,c,d){a|=0;b|=0;c|=0;d|=0;var e=0;Le=Le+1|0;for(x[a>>2]=Le;(e|0)<(d|0);){if(0==(x[c+(e<<3)>>2]|0))return x[c+(e<<3)>>2]=Le,x[c+((e<<3)+4)>>2]=b,x[c+((e<<3)+8)>>2]=0,xa=d|0,c|0;e=e+1|0}d=2*d|0;c=Ne(c|0,8*(d+1|0)|0)|0;c=Me(a|0,b|0,c|0,d|0)|0;xa=d|0;return c|0}function Oe(a,b){if(!ne())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?je&&ke.$e?Be(a,b):b.hg?(ge(Be,1,[a,b]),1):-2:-3:-4}
function Pe(a,b,c,d,e,g){Vd||(Vd=E(256));a={target:Y(a),Ne:g,Se:d,Ue:function(h){h=h||event;var m=h.target.id?h.target.id:"",n=Vd;I(me(h.target),n+0,128);I(m,n+128,128);Z(d,e,n,b)&&h.preventDefault()},Re:c};le(a)}
function Qe(a,b,c,d,e){Wd||(Wd=E(280));le({target:a,Ne:e,Se:d,Ue:function(g){g=g||event;var h=Wd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;x[h>>2]=n;x[h+4>>2]=ne();var r=n?m:$d,p=r&&r.id?r.id:"";I(me(r),h+8,128);I(p,h+136,128);x[h+264>>2]=r?r.clientWidth:0;x[h+268>>2]=r?r.clientHeight:0;x[h+272>>2]=screen.width;x[h+276>>2]=screen.height;n&&($d=m);Z(d,19,h,b)&&g.preventDefault()},Re:c})}
function Re(a,b,c,d,e){qe||(qe=E(1432));b={target:Y(2),$e:!0,Ne:e,Se:c,Ue:function(g){g=g||event;var h=qe;De(h,g.gamepad);Z(c,d,h,a)&&g.preventDefault()},Re:b};le(b)}
function Se(a,b,c,d,e,g){Rd||(Rd=E(164));a={target:Y(a),$e:!0,Ne:g,Se:d,Ue:function(h){h=h||event;var m=Rd;I(h.key?h.key:"",m+0,32);I(h.code?h.code:"",m+32,32);x[m+64>>2]=h.location;x[m+68>>2]=h.ctrlKey;x[m+72>>2]=h.shiftKey;x[m+76>>2]=h.altKey;x[m+80>>2]=h.metaKey;x[m+84>>2]=h.repeat;I(h.locale?h.locale:"",m+88,32);I(h.char?h.char:"",m+120,32);x[m+152>>2]=h.charCode;x[m+156>>2]=h.keyCode;x[m+160>>2]=h.which;Z(d,e,m,b)&&h.preventDefault()},Re:c};le(a)}
function Te(a,b,c){x[a>>2]=b.screenX;x[a+4>>2]=b.screenY;x[a+8>>2]=b.clientX;x[a+12>>2]=b.clientY;x[a+16>>2]=b.ctrlKey;x[a+20>>2]=b.shiftKey;x[a+24>>2]=b.altKey;x[a+28>>2]=b.metaKey;Ca[a+32>>1]=b.button;Ca[a+34>>1]=b.buttons;var d=b.movementY||b.screenY-be;x[a+36>>2]=b.movementX||b.screenX-ae;x[a+40>>2]=d;c=0>te.indexOf(c)?c.getBoundingClientRect():{left:0,top:0};x[a+44>>2]=b.clientX-c.left;x[a+48>>2]=b.clientY-c.top;"wheel"!==b.type&&"mousewheel"!==b.type&&(ae=b.screenX,be=b.screenY)}
function Ue(a,b,c,d,e,g){Sd||(Sd=E(64));a=Y(a);le({target:a,$e:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Ne:g,Se:d,Ue:function(h){h=h||event;Te(Sd,h,a);Z(d,e,Sd,b)&&h.preventDefault()},Re:c})}function Ve(a,b,c,d,e){Xd||(Xd=E(260));le({target:a,Ne:e,Se:d,Ue:function(g){g=g||event;var h=Xd,m=document.pointerLockElement||document.$f||document.Fg||document.Eg;x[h>>2]=!!m;var n=m&&m.id?m.id:"";I(me(m),h+4,128);I(n,h+132,128);Z(d,20,h,b)&&g.preventDefault()},Re:c})}
function We(a,b,c,d){Ud||(Ud=E(36));a=Y(a);le({target:a,Ne:"resize",Se:d,Ue:function(e){e=e||event;if(e.target==a){var g=Ud,h=document.body;x[g>>2]=e.detail;x[g+4>>2]=h.clientWidth;x[g+8>>2]=h.clientHeight;x[g+12>>2]=innerWidth;x[g+16>>2]=innerHeight;x[g+20>>2]=outerWidth;x[g+24>>2]=outerHeight;x[g+28>>2]=pageXOffset;x[g+32>>2]=pageYOffset;Z(d,10,g,b)&&e.preventDefault()}},Re:c})}
function Xe(a,b,c,d,e,g){Zd||(Zd=E(1684));a=Y(a);le({target:a,$e:"touchstart"==g||"touchend"==g,Ne:g,Se:d,Ue:function(h){h=h||event;for(var m={},n=0;n<h.touches.length;++n){var r=h.touches[n];r.If=!1;m[r.identifier]=r}for(n=0;n<h.changedTouches.length;++n)r=h.changedTouches[n],m[r.identifier]=r,r.If=!0;for(n=0;n<h.targetTouches.length;++n)r=h.targetTouches[n],m[r.identifier].ug=!0;var p=r=Zd;x[p+4>>2]=h.ctrlKey;x[p+8>>2]=h.shiftKey;x[p+12>>2]=h.altKey;x[p+16>>2]=h.metaKey;p+=20;var t=a.getBoundingClientRect(),
w=0;for(n in m){var v=m[n];x[p>>2]=v.identifier;x[p+4>>2]=v.screenX;x[p+8>>2]=v.screenY;x[p+12>>2]=v.clientX;x[p+16>>2]=v.clientY;x[p+20>>2]=v.pageX;x[p+24>>2]=v.pageY;x[p+28>>2]=v.If;x[p+32>>2]=v.ug;x[p+36>>2]=v.clientX-t.left;x[p+40>>2]=v.clientY-t.top;p+=52;if(32<=++w)break}x[r>>2]=w;Z(d,e,r,b)&&h.preventDefault()},Re:c})}
function Ye(a,b,c){var d=te[1];Yd||(Yd=E(8));le({target:d,Ne:"visibilitychange",Se:c,Ue:function(e){e=e||event;var g=Yd,h=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[g>>2]=document.hidden;x[g+4>>2]=h;Z(c,21,g,a)&&e.preventDefault()},Re:b})}
function Ze(a,b,c,d,e){function g(m){m=m||event;Te(Td,m,a);D[Td+64>>3]=m.wheelDeltaX||0;D[Td+72>>3]=-(m.wheelDeltaY||m.wheelDelta);D[Td+80>>3]=0;x[Td+88>>2]=0;Z(d,9,Td,b)&&m.preventDefault()}function h(m){m=m||event;var n=Td;Te(n,m,a);D[n+64>>3]=m.deltaX;D[n+72>>3]=m.deltaY;D[n+80>>3]=m.deltaZ;x[n+88>>2]=m.deltaMode;Z(d,9,n,b)&&m.preventDefault()}Td||(Td=E(96));le({target:a,$e:!0,Ne:e,Se:d,Ue:"wheel"==e?h:g,Re:c})}var $e={};
function af(){if(!bf){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da},b;for(b in $e)a[b]=$e[b];var c=[];for(b in a)c.push(b+"="+a[b]);bf=c}return bf}var bf,cf;f.requestFullscreen=function(a,b,c){Wb(a,b,c)};f.requestAnimationFrame=function(a){xb(a)};f.setCanvasSize=function(a,b,c){Yb(f.canvas,a,b);c||Zb()};f.pauseMainLoop=function(){tb=null;Ab++};
f.resumeMainLoop=function(){Ab++;var a=qb,b=rb,c=sb;sb=null;yb(c,0,!1,zb,!0);pb(a,b);tb()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Pb(a,b,c,d)};ha?vb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?vb=dateNow:vb=function(){return performance.now()};$c();yc=Array(4096);Pc(N,"/");O("/tmp");O("/home");O("/home/web_user");
(function(){O("/dev");mc(259,{read:function(){return 0},write:function(d,e,g,h){return h}});Rc("/dev/null",259);lc(1280,oc);lc(1536,pc);Rc("/dev/tty",1280);Rc("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ha)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){q("random_device")});gd("/dev","random",b);gd("/dev","urandom",b);
O("/dev/shm");O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");Pc({We:function(){var a=rc("/proc/self","fd",16895,73);a.Je={lookup:function(b,c){var d=wc[+c];if(!d)throw new M(8);b={parent:null,We:{Uf:"fake"},Je:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");f.FS_createFolder=cd;f.FS_createPath=dd;f.FS_createDataFile=fd;f.FS_createPreloadedFile=kd;f.FS_createLazyFile=jd;f.FS_createLink=hd;f.FS_createDevice=gd;f.FS_unlink=Tc;
for(var K,df=new Float32Array(256),ef=0;256>ef;ef++)Ld[ef]=df.subarray(0,ef+1);var ff=new Int32Array(256);for(ef=0;256>ef;ef++)Md[ef]=ff.subarray(0,ef+1);for(var gf=0;32>gf;gf++)Ee.push(Array(gf));function mb(a,b){var c=Array(Oa(a)+1);a=Na(a,c,0,c.length);b&&(c.length=a);return c}
var pf={b:function(a,b,c,d){q("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},ga:function(){},r:function(a,b){md=b;try{var c=nd();switch(P()){case 0:var d=P();return 0>d?-28:Vc(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=P(),c.flags|=d,0;case 12:return d=P(),Ca[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return dc(28),-1;default:return-28}}catch(e){return"undefined"!==typeof ld&&e instanceof
M||q(e),-e.Ye}},ha:function(a,b){md=b;try{var c=H(P()),d=P(),e=P();return Vc(c,d,e).fd}catch(g){return"undefined"!==typeof ld&&g instanceof M||q(g),-g.Ye}},fa:function(a,b){md=b;try{var c=nd(),d=P();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=P();return x[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=P();if(!c.Ke.qg)throw new M(59);return c.Ke.qg(c,d,a);case 21523:return c.tty?
0:-59;case 21524:return c.tty?0:-59;default:q("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof ld&&g instanceof M||q(g),-g.Ye}},l:function(){},n:function(a,b){if(0===a)a=Date.now();else if(1===a&&od)a=vb();else return dc(28),-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},la:function(){return pd.apply(null,arguments)},ma:function(){return pd.apply(null,arguments)},x:function(){return pd.apply(null,arguments)},Da:function(a){if(12448==a)return Q=12288,1;Q=12300;return 0},Ia:function(a,
b,c,d,e){if(62E3!=a)Q=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)R.alpha=0<x[b+4>>2];else if(12325==a)R.depth=0<x[b+4>>2];else if(12326==a)R.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],R.antialias=0<a;else if(12338==a)a=x[b+4>>2],R.antialias=1==a;else if(12544==a)R.Pg=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),Q=12288,c=1):(Q=12300,c=0)}return c},ua:function(a,b,c,d){if(62E3!=a)return Q=12296,0;for(a=1;;){b=x[d>>2];if(12440==b)a=x[d+4>>
2];else if(12344==b)break;else return Q=12292,0;d+=8}if(2!=a)return Q=12293,0;R.Sf=a-1;R.Qg=0;vd=Rb(f.canvas,R);if(0!=vd)return Q=12288,Sb(vd),f.Bg=!0,Hb.forEach(function(e){e()}),Sb(null),62004;Q=12297;return 0},wa:function(a,b){if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;Q=12288;return 62006},va:function(a,b){if(62E3!=a)return Q=12296,0;if(62004!=b)return Q=12294,0;a=vd;Gd===J[a]&&(Gd=null);if("object"===typeof oe)for(var c=J[a].Xe.canvas,d=0;d<ee.length;++d)ee[d].target!=c||fe(d--);
J[a]&&J[a].Xe.canvas&&(J[a].Xe.canvas.ff=void 0);hf(J[a]);J[a]=null;Q=12288;rd==b&&(rd=0);return 1},xa:function(a,b){if(62E3!=a)return Q=12296,0;if(62006!=b)return Q=12301,1;sd==b&&(sd=0);td==b&&(td=0);Q=12288;return 1},Ja:function(a,b,c,d){if(62E3!=a)return Q=12296,0;if(62002!=b)return Q=12293,0;if(!d)return Q=12300,0;Q=12288;switch(c){case 12320:return x[d>>2]=R.alpha?32:24,1;case 12321:return x[d>>2]=R.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>2]=8,1;case 12324:return x[d>>
2]=8,1;case 12325:return x[d>>2]=R.depth?24:0,1;case 12326:return x[d>>2]=R.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>2]=12344,1;case 12337:return x[d>>2]=R.antialias?4:0,1;case 12338:return x[d>>2]=R.antialias?1:0,1;case 12339:return x[d>>2]=4,
1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return Q=12292,0}},U:function(){Q=12288;return 62E3},ta:function(){return Q},Ea:function(a){return jf(a)},Fa:function(a,b,c){if(62E3==a)return b&&(x[b>>2]=1),c&&(x[c>>2]=
4),qd=!0,Q=12288,1;Q=12296;return 0},ya:function(a,b,c,d){if(62E3!=a)return Q=12296,0;if(0!=d&&62004!=d)return Q=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return Q=12301,0;Sb(d?vd:null);rd=d;td=b;sd=c;Q=12288;return 1},sa:function(a,b){if(62E3!=a)return Q=12296,0;Q=12288;if(ud[b])return ud[b];switch(b){case 12371:a=Ka(mb("Emscripten"));break;case 12372:a=Ka(mb("1.4 Emscripten EGL"));break;case 12373:a=Ka(mb(""));break;case 12429:a=Ka(mb("OpenGL_ES"));break;default:return Q=12300,0}return ud[b]=a},
za:function(){if(qd)if(f.Te)if(f.Te.isContextLost())Q=12302;else return Q=12288,1;else Q=12290;else Q=12289;return 0},Aa:function(a,b){if(62E3!=a)return Q=12296,0;0==b?pb(0,0):pb(1,b);Q=12288;return 1},Ha:function(a){if(62E3!=a)return Q=12296,0;td=sd=rd=0;qd=!1;Q=12288;return 1},Ca:function(){return Qd.apply(null,arguments)},Ba:function(){Q=12288;return 1},a:function(a,b,c){cf||(cf=[]);var d=cf;d.length=0;for(var e;e=F[b++];)100===e||102===e?(c=c+7&-8,d.push(D[c>>3]),c+=8):(c=c+3&-4,d.push(x[c>>2]),
c+=4);return nb[a].apply(null,d)},na:function(){if(!ne())return-1;he(Be);var a=te[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ra:function(){he(Ce);if(document.exitPointerLock)document.exitPointerLock();else if(document.bf)document.bf();else return-1;return 0},j:function(){return devicePixelRatio||1},d:function(a,b,c){a=Y(a);if(!a)return-4;a=a.getBoundingClientRect();D[b>>3]=
a.width;D[c>>3]=a.height;return 0},v:function(a,b){if(0>a||a>=pe.length)return-5;if(!pe[a])return-7;De(b,pe[a]);return 0},p:vb,ka:function(){return pe.length},xd:function(a){K.activeTexture(a)},wd:function(a,b){K.attachShader(S[a],U[b])},X:function(a,b){K.Qe.beginQueryEXT(a,V[b])},vd:function(a,b,c){K.bindAttribLocation(S[a],b,H(c))},ud:function(a,b){K.bindBuffer(a,Bd[b])},td:function(a,b){K.bindFramebuffer(a,Cd[b])},sd:function(a,b){K.bindRenderbuffer(a,Dd[b])},rd:function(a,b){K.bindTexture(a,Ed[b])},
Gd:function(a){K.bindVertexArray(Fd[a])},qd:function(a,b,c,d){K.blendColor(a,b,c,d)},pd:function(a){K.blendEquation(a)},od:function(a,b){K.blendEquationSeparate(a,b)},nd:function(a,b){K.blendFunc(a,b)},md:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},ld:function(a,b,c,d){K.bufferData(a,c?F.subarray(c,c+b):b,d)},kd:function(a,b,c,d){K.bufferSubData(a,b,F.subarray(d,d+c))},jd:function(a){return K.checkFramebufferStatus(a)},id:function(a){K.clear(a)},gd:function(a,b,c,d){K.clearColor(a,b,c,d)},fd:function(a){K.clearDepth(a)},
ed:function(a){K.clearStencil(a)},dd:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},cd:function(a){K.compileShader(U[a])},bd:function(a,b,c,d,e,g,h,m){K.compressedTexImage2D(a,b,c,d,e,g,m?F.subarray(m,m+h):null)},ad:function(a,b,c,d,e,g,h,m,n){K.compressedTexSubImage2D(a,b,c,d,e,g,h,n?F.subarray(n,n+m):null)},$c:function(a,b,c,d,e,g,h,m){K.copyTexImage2D(a,b,c,d,e,g,h,m)},_c:function(a,b,c,d,e,g,h,m){K.copyTexSubImage2D(a,b,c,d,e,g,h,m)},Zc:function(){var a=Kd(S),b=K.createProgram();b.name=a;S[a]=
b;return a},Yc:function(a){var b=Kd(U);U[b]=K.createShader(a);return b},Xc:function(a){K.cullFace(a)},Wc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Bd[d];e&&(K.deleteBuffer(e),e.name=0,Bd[d]=null,d==Od&&(Od=0),d==Pd&&(Pd=0))}},Vc:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Cd[d];e&&(K.deleteFramebuffer(e),e.name=0,Cd[d]=null)}},Uc:function(a){if(a){var b=S[a];b?(K.deleteProgram(b),b.name=0,S[a]=null,Hd[a]=null):W(1281)}},Z:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],
e=V[d];e&&(K.Qe.deleteQueryEXT(e),V[d]=null)}},Tc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Dd[d];e&&(K.deleteRenderbuffer(e),e.name=0,Dd[d]=null)}},Sc:function(a){if(a){var b=U[a];b?(K.deleteShader(b),U[a]=null):W(1281)}},Rc:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ed[d];e&&(K.deleteTexture(e),e.name=0,Ed[d]=null)}},Fd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(Fd[d]);Fd[d]=null}},Qc:function(a){K.depthFunc(a)},Pc:function(a){K.depthMask(!!a)},
Oc:function(a,b){K.depthRange(a,b)},Nc:function(a,b){K.detachShader(S[a],U[b])},Mc:function(a){K.disable(a)},Lc:function(a){K.disableVertexAttribArray(a)},Kc:function(a,b,c){K.drawArrays(a,b,c)},Ad:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Bd:function(a,b){for(var c=Ee[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},Jc:function(a,b,c,d){K.drawElements(a,b,c,d)},zd:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Ic:function(a){K.enable(a)},Hc:function(a){K.enableVertexAttribArray(a)},
W:function(a){K.Qe.endQueryEXT(a)},Gc:function(){K.finish()},Fc:function(){K.flush()},Ec:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,Dd[d])},Dc:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,Ed[d],e)},Cc:function(a){K.frontFace(a)},Bc:function(a,b){Fe(a,b,"createBuffer",Bd)},zc:function(a,b){Fe(a,b,"createFramebuffer",Cd)},_:function(a,b){for(var c=0;c<a;c++){var d=K.Qe.createQueryEXT();if(!d){for(W(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Kd(V);d.name=e;V[e]=d;x[b+4*c>>2]=e}},yc:function(a,
b){Fe(a,b,"createRenderbuffer",Dd)},xc:function(a,b){Fe(a,b,"createTexture",Ed)},Ed:function(a,b){Fe(a,b,"createVertexArray",Fd)},Ac:function(a){K.generateMipmap(a)},wc:function(a,b,c,d,e,g,h){a=S[a];if(a=K.getActiveAttrib(a,b))c=0<c&&h?I(a.name,h,c):0,d&&(x[d>>2]=c),e&&(x[e>>2]=a.size),g&&(x[g>>2]=a.type)},vc:function(a,b,c,d,e,g,h){a=S[a];if(a=K.getActiveUniform(a,b))c=0<c&&h?I(a.name,h,c):0,d&&(x[d>>2]=c),e&&(x[e>>2]=a.size),g&&(x[g>>2]=a.type)},uc:function(a,b,c,d){a=K.getAttachedShaders(S[a]);
var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=U.indexOf(a[b])},tc:function(a,b){return K.getAttribLocation(S[a],H(b))},sc:function(a,b){Ge(a,b,4)},rc:function(a,b,c){c?x[c>>2]=K.getBufferParameter(a,b):W(1281)},qc:function(){var a=K.getError()||Ad;Ad=0;return a},pc:function(a,b){Ge(a,b,2)},oc:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},nc:function(a,b){Ge(a,b,0)},lc:function(a,b,
c,d){a=K.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(x[c>>2]=b)},mc:function(a,b,c){if(c)if(a>=zd)W(1281);else{var d=Hd[a];if(d)if(35716==b)a=K.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.zf;else if(35722==b){if(-1==d.gf){a=S[a];var e=K.getProgramParameter(a,35721);for(b=d.gf=0;b<e;++b)d.gf=Math.max(d.gf,K.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.gf}else if(35381==b){if(-1==d.hf)for(a=S[a],e=K.getProgramParameter(a,
35382),b=d.hf=0;b<e;++b)d.hf=Math.max(d.hf,K.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.hf}else x[c>>2]=K.getProgramParameter(S[a],b);else W(1282)}else W(1281)},Id:function(a,b,c){if(c){a=K.Qe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y=[d>>>0,(A=d,1<=+Da(A)?0<A?(Ea(+Fa(A/4294967296),4294967295)|0)>>>0:~~+Ga((A-+(~~A>>>0))/4294967296)>>>0:0)];x[c>>2]=y[0];x[c+4>>2]=y[1]}else W(1281)},Kd:function(a,b,c){if(c){a=K.Qe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;x[c>>2]=d}else W(1281)},Hd:function(a,b,c){if(c){a=K.Qe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y=[d>>>0,(A=d,1<=+Da(A)?0<A?(Ea(+Fa(A/4294967296),4294967295)|0)>>>0:~~+Ga((A-+(~~A>>>0))/4294967296)>>>0:0)];x[c>>2]=y[0];x[c+4>>2]=y[1]}else W(1281)},Jd:function(a,b,c){if(c){a=K.Qe.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else W(1281)},Ld:function(a,b,c){c?x[c>>2]=K.Qe.getQueryEXT(a,b):W(1281)},kc:function(a,b,c){c?x[c>>2]=K.getRenderbufferParameter(a,
b):W(1281)},ic:function(a,b,c,d){a=K.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?I(a,d,b):0;c&&(x[c>>2]=b)},hc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},gc:function(a,b,c,d){if(a=K.getShaderSource(U[a]))b=0<b&&d?I(a,d,b):0,c&&(x[c>>2]=b)},jc:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=K.getShaderSource(U[a]),x[c>>2]=null===a||0==a.length?
0:a.length+1):x[c>>2]=K.getShaderParameter(U[a],b):W(1281)},fc:function(a){if(Id[a])return Id[a];switch(a){case 7939:var b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=He(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||W(1280);b=He(b);break;case 7938:b=He("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+=
"0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=He(b);break;default:return W(1280),0}return Id[a]=b},ec:function(a,b,c){c?B[c>>2]=K.getTexParameter(a,b):W(1281)},dc:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,b):W(1281)},ac:function(a,b){b=H(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Hd[a]&&Hd[a].Zf[b])&&0<=c&&c<a[0]?a[1]+c:-1},cc:function(a,b,c){Ie(a,b,c,2)},bc:function(a,b,c){Ie(a,b,c,0)},Zb:function(a,b,c){c?x[c>>2]=
K.getVertexAttribOffset(a,b):W(1281)},$b:function(a,b,c){Je(a,b,c,2)},_b:function(a,b,c){Je(a,b,c,5)},Yb:function(a,b){K.hint(a,b)},Xb:function(a){return(a=Bd[a])?K.isBuffer(a):0},Wb:function(a){return K.isEnabled(a)},Vb:function(a){return(a=Cd[a])?K.isFramebuffer(a):0},Ub:function(a){return(a=S[a])?K.isProgram(a):0},Y:function(a){return(a=V[a])?K.Qe.isQueryEXT(a):0},Tb:function(a){return(a=Dd[a])?K.isRenderbuffer(a):0},Rb:function(a){return(a=U[a])?K.isShader(a):0},Qb:function(a){return(a=Ed[a])?
K.isTexture(a):0},Dd:function(a){return(a=Fd[a])?K.isVertexArray(a):0},Pb:function(a){K.lineWidth(a)},Ob:function(a){K.linkProgram(S[a]);var b=S[a];a=Hd[a]={Zf:{},zf:0,gf:-1,hf:-1};for(var c=a.Zf,d=K.getProgramParameter(b,35718),e=0;e<d;++e){var g=K.getActiveUniform(b,e),h=g.name;a.zf=Math.max(a.zf,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var m=K.getUniformLocation(b,h);if(m){var n=Kd(T);c[h]=[g.size,n];T[n]=m;for(var r=1;r<g.size;++r)m=K.getUniformLocation(b,h+"["+r+"]"),n=
Kd(T),T[n]=m}}},Nb:function(a,b){3317==a&&(Jd=b);K.pixelStorei(a,b)},Mb:function(a,b){K.polygonOffset(a,b)},Md:function(a,b){K.Qe.queryCounterEXT(V[a],b)},Lb:function(a,b,c,d,e,g,h){(h=Ke(g,e,c,d,h))?K.readPixels(a,b,c,d,e,g,h):W(1280)},Kb:function(){},Jb:function(a,b,c,d){K.renderbufferStorage(a,b,c,d)},Ib:function(a,b){K.sampleCoverage(a,!!b)},Gb:function(a,b,c,d){K.scissor(a,b,c,d)},Fb:function(){W(1280)},Eb:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?x[d+4*g>>2]:-1;e+=H(x[c+4*g>>2],0>
h?void 0:h)}K.shaderSource(U[a],e)},Db:function(a,b,c){K.stencilFunc(a,b,c)},Cb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Bb:function(a){K.stencilMask(a)},Ab:function(a,b){K.stencilMaskSeparate(a,b)},zb:function(a,b,c){K.stencilOp(a,b,c)},yb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},xb:function(a,b,c,d,e,g,h,m,n){K.texImage2D(a,b,c,d,e,g,h,m,n?Ke(m,h,d,e,n):null)},vb:function(a,b,c){K.texParameterf(a,b,c)},ub:function(a,b,c){K.texParameterf(a,b,B[c>>2])},tb:function(a,b,c){K.texParameteri(a,
b,c)},sb:function(a,b,c){K.texParameteri(a,b,x[c>>2])},rb:function(a,b,c,d,e,g,h,m,n){var r=null;n&&(r=Ke(m,h,e,g,n));K.texSubImage2D(a,b,c,d,e,g,h,m,r)},qb:function(a,b){K.uniform1f(T[a],b)},pb:function(a,b,c){if(256>=b)for(var d=Ld[b-1],e=0;e<b;++e)d[e]=B[c+4*e>>2];else d=B.subarray(c>>2,c+4*b>>2);K.uniform1fv(T[a],d)},ob:function(a,b){K.uniform1i(T[a],b)},nb:function(a,b,c){if(256>=b)for(var d=Md[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);K.uniform1iv(T[a],d)},mb:function(a,
b,c){K.uniform2f(T[a],b,c)},kb:function(a,b,c){if(256>=2*b)for(var d=Ld[2*b-1],e=0;e<2*b;e+=2)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2];else d=B.subarray(c>>2,c+8*b>>2);K.uniform2fv(T[a],d)},jb:function(a,b,c){K.uniform2i(T[a],b,c)},ib:function(a,b,c){if(256>=2*b)for(var d=Md[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);K.uniform2iv(T[a],d)},hb:function(a,b,c,d){K.uniform3f(T[a],b,c,d)},gb:function(a,b,c){if(256>=3*b)for(var d=Ld[3*b-1],e=0;e<3*b;e+=
3)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+4)>>2],d[e+2]=B[c+(4*e+8)>>2];else d=B.subarray(c>>2,c+12*b>>2);K.uniform3fv(T[a],d)},fb:function(a,b,c,d){K.uniform3i(T[a],b,c,d)},eb:function(a,b,c){if(256>=3*b)for(var d=Md[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3iv(T[a],d)},db:function(a,b,c,d,e){K.uniform4f(T[a],b,c,d,e)},cb:function(a,b,c){if(256>=4*b)for(var d=Ld[4*b-1],e=0;e<4*b;e+=4)d[e]=B[c+4*e>>2],d[e+1]=B[c+(4*e+
4)>>2],d[e+2]=B[c+(4*e+8)>>2],d[e+3]=B[c+(4*e+12)>>2];else d=B.subarray(c>>2,c+16*b>>2);K.uniform4fv(T[a],d)},bb:function(a,b,c,d,e){K.uniform4i(T[a],b,c,d,e)},$a:function(a,b,c){if(256>=4*b)for(var d=Md[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);K.uniform4iv(T[a],d)},_a:function(a,b,c,d){if(256>=4*b)for(var e=Ld[4*b-1],g=0;g<4*b;g+=4)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+
3]=B[d+(4*g+12)>>2];else e=B.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(T[a],!!c,e)},Za:function(a,b,c,d){if(256>=9*b)for(var e=Ld[9*b-1],g=0;g<9*b;g+=9)e[g]=B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>2],e[g+4]=B[d+(4*g+16)>>2],e[g+5]=B[d+(4*g+20)>>2],e[g+6]=B[d+(4*g+24)>>2],e[g+7]=B[d+(4*g+28)>>2],e[g+8]=B[d+(4*g+32)>>2];else e=B.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(T[a],!!c,e)},Ya:function(a,b,c,d){if(256>=16*b)for(var e=Ld[16*b-1],g=0;g<16*b;g+=16)e[g]=
B[d+4*g>>2],e[g+1]=B[d+(4*g+4)>>2],e[g+2]=B[d+(4*g+8)>>2],e[g+3]=B[d+(4*g+12)>>2],e[g+4]=B[d+(4*g+16)>>2],e[g+5]=B[d+(4*g+20)>>2],e[g+6]=B[d+(4*g+24)>>2],e[g+7]=B[d+(4*g+28)>>2],e[g+8]=B[d+(4*g+32)>>2],e[g+9]=B[d+(4*g+36)>>2],e[g+10]=B[d+(4*g+40)>>2],e[g+11]=B[d+(4*g+44)>>2],e[g+12]=B[d+(4*g+48)>>2],e[g+13]=B[d+(4*g+52)>>2],e[g+14]=B[d+(4*g+56)>>2],e[g+15]=B[d+(4*g+60)>>2];else e=B.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(T[a],!!c,e)},Xa:function(a){K.useProgram(S[a])},Wa:function(a){K.validateProgram(S[a])},
Va:function(a,b){K.vertexAttrib1f(a,b)},Ua:function(a,b){K.vertexAttrib1f(a,B[b>>2])},Ta:function(a,b,c){K.vertexAttrib2f(a,b,c)},Sa:function(a,b){K.vertexAttrib2f(a,B[b>>2],B[b+4>>2])},Ra:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},Qa:function(a,b){K.vertexAttrib3f(a,B[b>>2],B[b+4>>2],B[b+8>>2])},Pa:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},Oa:function(a,b){K.vertexAttrib4f(a,B[b>>2],B[b+4>>2],B[b+8>>2],B[b+12>>2])},yd:function(a,b){K.vertexAttribDivisor(a,b)},Na:function(a,b,c,d,e,g){K.vertexAttribPointer(a,
b,c,!!d,e,g)},Ma:function(a,b,c,d){K.viewport(a,b,c,d)},h:function(a,b){kf(a,b||1);throw"longjmp";},$:function(a,b,c){F.set(F.subarray(b,b+c),a)},oa:function(a,b,c){var d={};d.Cf=x[c>>2];d.tf=x[c+4>>2];d.kg=x[c+8>>2];d.hg=b;d.mf=x[c+12>>2];d.Hf=x[c+16>>2];re=d;return Oe(a,d)},S:function(a,b){a=Y(a);return a?a.requestPointerLock||a.rf?je&&ke.$e?Ce(a):b?(ge(Ce,2,[a]),1):-2:-1:-4},aa:function(){q("OOM")},w:function(){return(pe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?
navigator.webkitGetGamepads():null)?0:-1},K:function(a,b,c,d){Pe(a,b,c,d,12,"blur");return 0},g:xe,o:function(a,b,c){a=Y(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},L:function(a,b,c,d){Pe(a,b,c,d,13,"focus");return 0},A:function(a,b,c,d){if(!ne())return-1;a=Y(a);if(!a)return-4;Qe(a,b,c,d,"fullscreenchange");Qe(a,b,c,d,"webkitfullscreenchange");return 0},u:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Re(a,b,c,26,"gamepadconnected");return 0},
t:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Re(a,b,c,27,"gamepaddisconnected");return 0},D:function(a,b,c,d){Se(a,b,c,d,2,"keydown");return 0},B:function(a,b,c,d){Se(a,b,c,d,1,"keypress");return 0},C:function(a,b,c,d){Se(a,b,c,d,3,"keyup");return 0},hd:function(a,b,c,d){yb(a,c,d,b)},Q:function(a,b,c,d){Ue(a,b,c,d,5,"mousedown");return 0},O:function(a,b,c,d){Ue(a,b,c,d,33,"mouseenter");return 0},N:function(a,b,c,d){Ue(a,b,c,d,34,"mouseleave");return 0},R:function(a,
b,c,d){Ue(a,b,c,d,8,"mousemove");return 0},P:function(a,b,c,d){Ue(a,b,c,d,6,"mouseup");return 0},E:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.bf||document.body.$f||document.body.rf))return-1;a=Y(a);if(!a)return-4;Ve(a,b,c,d,"pointerlockchange");Ve(a,b,c,d,"mozpointerlockchange");Ve(a,b,c,d,"webkitpointerlockchange");Ve(a,b,c,d,"mspointerlockchange");return 0},z:function(a,b,c,d){We(a,b,c,d);return 0},F:function(a,b,c,d){Xe(a,b,c,d,25,"touchcancel");
return 0},H:function(a,b,c,d){Xe(a,b,c,d,23,"touchend");return 0},G:function(a,b,c,d){Xe(a,b,c,d,24,"touchmove");return 0},J:function(a,b,c,d){Xe(a,b,c,d,22,"touchstart");return 0},y:function(a,b,c){if(!te[1])return-4;Ye(a,b,c);return 0},M:function(a,b,c,d){a=Y(a);return"undefined"!==typeof a.onwheel?(Ze(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Ze(a,b,c,d,"mousewheel"),0):-1},ba:function(a,b){var c=0;af().forEach(function(d,e){var g=b+c;e=x[a+4*e>>2]=g;for(g=0;g<d.length;++g)u[e++>>
0]=d.charCodeAt(g);u[e>>0]=0;c+=d.length+1});return 0},ca:function(a,b){var c=af();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},s:function(a){try{var b=nd(a);Xc(b);return 0}catch(c){return"undefined"!==typeof ld&&c instanceof M||q(c),c.Ye}},ea:function(a,b,c,d){try{a:{for(var e=nd(a),g=a=0;g<c;g++){var h=x[b+(8*g+4)>>2],m=e,n=x[b+8*g>>2],r=h,p=void 0,t=u;if(0>r||0>p)throw new M(28);if(null===m.fd)throw new M(8);if(1===(m.flags&2097155))throw new M(8);if(16384===
(m.node.mode&61440))throw new M(31);if(!m.Ke.read)throw new M(28);var w="undefined"!==typeof p;if(!w)p=m.position;else if(!m.seekable)throw new M(70);var v=m.Ke.read(m,t,n,r,p);w||(m.position+=v);var z=v;if(0>z){var C=-1;break a}a+=z;if(z<h)break}C=a}x[d>>2]=C;return 0}catch(G){return"undefined"!==typeof ld&&G instanceof M||q(G),G.Ye}},La:function(a,b,c,d,e){try{var g=nd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Yc(g,a,d);y=[g.position>>>0,(A=g.position,1<=+Da(A)?
0<A?(Ea(+Fa(A/4294967296),4294967295)|0)>>>0:~~+Ga((A-+(~~A>>>0))/4294967296)>>>0:0)];x[e>>2]=y[0];x[e+4>>2]=y[1];g.xf&&0===a&&0===d&&(g.xf=null);return 0}catch(h){return"undefined"!==typeof ld&&h instanceof M||q(h),h.Ye}},da:function(a,b,c,d){try{a:{for(var e=nd(a),g=a=0;g<c;g++){var h=Zc(e,u,x[b+8*g>>2],x[b+(8*g+4)>>2],void 0);if(0>h){var m=-1;break a}a+=h}m=a}x[d>>2]=m;return 0}catch(n){return"undefined"!==typeof ld&&n instanceof M||q(n),n.Ye}},e:function(){return xa|0},m:function(a){var b=Date.now();
x[a>>2]=b/1E3|0;x[a+4>>2]=b%1E3*1E3|0;return 0},Od:function(a){K.activeTexture(a)},q:function(a,b){K.bindTexture(a,Ed[b])},Ga:function(a,b){K.blendFunc(a,b)},ja:function(a){K.clear(a)},pa:function(a,b,c,d){K.clearColor(a,b,c,d)},qa:function(a){K.cullFace(a)},Sb:function(a,b,c,d){K.drawElements(a,b,c,d)},T:function(a){K.enable(a)},Nd:function(a,b){Fe(a,b,"createTexture",Ed)},I:function(a,b){Ge(a,b,0)},Cd:function(a,b,c,d,e,g,h,m,n){K.texImage2D(a,b,c,d,e,g,h,m,n?Ke(m,h,d,e,n):null)},k:function(a,b,
c){K.texParameteri(a,b,c)},Pd:function(a,b,c,d){K.viewport(a,b,c,d)},Hb:lf,lb:mf,wb:nf,ab:of,memory:Ha,ia:function(a,b){if(0===a)return dc(28),-1;var c=x[a>>2];a=x[a+4>>2];if(0>a||999999999<a||0>c)return dc(28),-1;0!==b&&(x[b>>2]=0,x[b+4>>2]=0);b=(1E6*c+a/1E3)/1E3;if((fa||l)&&self.performance&&self.performance.now)for(c=self.performance.now();self.performance.now()-c<b;);else for(c=Date.now();Date.now()-c<b;);return 0},V:Me,f:function(a){xa=a|0},c:function(){return 0},Ka:function(){return 0},table:Ia,
i:function(a,b,c){a|=0;b|=0;c|=0;for(var d=0,e;(d|0)<(c|0);){e=x[b+(d<<3)>>2]|0;if(0==(e|0))break;if((e|0)==(a|0))return x[b+((d<<3)+4)>>2]|0;d=d+1|0}return 0}},qf=function(){function a(e){f.asm=e.exports;gb("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return lb().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){k("failed to asynchronously prepare wasm: "+g);q(g)})}var d={a:pf};fb("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(za||"function"!==typeof WebAssembly.instantiateStreaming||hb()||"function"!==typeof fetch)return c(b);fetch(ib,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){k("wasm streaming compile failed: "+g);k("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();f.asm=qf;
var ob=f.___wasm_call_ctors=function(){return(ob=f.___wasm_call_ctors=f.asm.Qd).apply(null,arguments)},hf=f._free=function(){return(hf=f._free=f.asm.Rd).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Sd).apply(null,arguments)};var Ne=f._realloc=function(){return(Ne=f._realloc=f.asm.Td).apply(null,arguments)},E=f._malloc=function(){return(E=f._malloc=f.asm.Ud).apply(null,arguments)};f.___errno_location=function(){return(f.___errno_location=f.asm.Vd).apply(null,arguments)};
var kf=f._setThrew=function(){return(kf=f._setThrew=f.asm.Wd).apply(null,arguments)},jf=f._emscripten_GetProcAddress=function(){return(jf=f._emscripten_GetProcAddress=f.asm.Xd).apply(null,arguments)},rf=f.dynCall_vi=function(){return(rf=f.dynCall_vi=f.asm.Yd).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.Zd).apply(null,arguments)};
var sf=f.dynCall_iii=function(){return(sf=f.dynCall_iii=f.asm._d).apply(null,arguments)},Z=f.dynCall_iiii=function(){return(Z=f.dynCall_iiii=f.asm.$d).apply(null,arguments)},tf=f.dynCall_iiiii=function(){return(tf=f.dynCall_iiiii=f.asm.ae).apply(null,arguments)},ve=f.stackSave=function(){return(ve=f.stackSave=f.asm.be).apply(null,arguments)},Qa=f.stackAlloc=function(){return(Qa=f.stackAlloc=f.asm.ce).apply(null,arguments)},we=f.stackRestore=function(){return(we=f.stackRestore=f.asm.de).apply(null,
arguments)};f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.ee).apply(null,arguments)};f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.fe).apply(null,arguments)};f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.ge).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.he).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.ie).apply(null,arguments)};f.dynCall_iiiiiiiiii=function(){return(f.dynCall_iiiiiiiiii=f.asm.je).apply(null,arguments)};
f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.ke).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.le).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.me).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.ne).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.oe).apply(null,arguments)};f.dynCall_ji=function(){return(f.dynCall_ji=f.asm.pe).apply(null,arguments)};
f.dynCall_iiiiidii=function(){return(f.dynCall_iiiiidii=f.asm.qe).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.re).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.se).apply(null,arguments)};f.dynCall_viiiiiiiiiii=function(){return(f.dynCall_viiiiiiiiiii=f.asm.te).apply(null,arguments)};f.dynCall_i=function(){return(f.dynCall_i=f.asm.ue).apply(null,arguments)};
f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.ve).apply(null,arguments)};f.dynCall_vffff=function(){return(f.dynCall_vffff=f.asm.we).apply(null,arguments)};f.dynCall_vf=function(){return(f.dynCall_vf=f.asm.xe).apply(null,arguments)};f.dynCall_viiiiiiii=function(){return(f.dynCall_viiiiiiii=f.asm.ye).apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return(f.dynCall_viiiiiiiii=f.asm.ze).apply(null,arguments)};f.dynCall_vff=function(){return(f.dynCall_vff=f.asm.Ae).apply(null,arguments)};
f.dynCall_vfi=function(){return(f.dynCall_vfi=f.asm.Be).apply(null,arguments)};f.dynCall_viif=function(){return(f.dynCall_viif=f.asm.Ce).apply(null,arguments)};f.dynCall_vif=function(){return(f.dynCall_vif=f.asm.De).apply(null,arguments)};f.dynCall_viff=function(){return(f.dynCall_viff=f.asm.Ee).apply(null,arguments)};f.dynCall_vifff=function(){return(f.dynCall_vifff=f.asm.Fe).apply(null,arguments)};f.dynCall_viffff=function(){return(f.dynCall_viffff=f.asm.Ge).apply(null,arguments)};
f.dynCall_vjj=function(){return(f.dynCall_vjj=f.asm.He).apply(null,arguments)};function lf(a,b,c){var d=ve();try{return sf(a,b,c)}catch(e){we(d);if(e!==e+0&&"longjmp"!==e)throw e;kf(1,0)}}function nf(a,b,c,d,e){var g=ve();try{return tf(a,b,c,d,e)}catch(h){we(g);if(h!==h+0&&"longjmp"!==h)throw h;kf(1,0)}}function mf(a,b,c,d){var e=ve();try{return Z(a,b,c,d)}catch(g){we(e);if(g!==g+0&&"longjmp"!==g)throw g;kf(1,0)}}
function of(a,b){var c=ve();try{rf(a,b)}catch(d){we(c);if(d!==d+0&&"longjmp"!==d)throw d;kf(1,0)}}f.asm=qf;f.getMemory=function(a){if(ab)var b=E(a);else b=x[40884],a=b+a+15&-16,a>u.length&&q(),x[40884]=a;return b};f.addRunDependency=fb;f.removeRunDependency=gb;f.FS_createFolder=cd;f.FS_createPath=dd;f.FS_createDataFile=fd;f.FS_createPreloadedFile=kd;f.FS_createLazyFile=jd;f.FS_createLink=hd;f.FS_createDevice=gd;f.FS_unlink=Tc;f.calledRun=uf;var uf;
function sa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}eb=function vf(){uf||wf();uf||(eb=vf)};
function wf(a){function b(){if(!uf&&(uf=!0,f.calledRun=!0,!Ja)){ab=!0;f.noFSInit||ad||(ad=!0,$c(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?gd("/dev","stdin",f.stdin):Sc("/dev/tty","/dev/stdin"),f.stdout?gd("/dev","stdout",null,f.stdout):Sc("/dev/tty","/dev/stdout"),f.stderr?gd("/dev","stderr",null,f.stderr):Sc("/dev/tty1","/dev/stderr"),Vc("/dev/stdin","r"),Vc("/dev/stdout","w"),Vc("/dev/stderr","w"));Va(Xa);zc=!1;Va(Ya);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(xf){var c=
a,d=f._main;c=c||[];var e=c.length+1,g=Qa(4*(e+1));x[g>>2]=Pa(da);for(var h=1;h<e;h++)x[(g>>2)+h]=Pa(c[h-1]);x[(g>>2)+e]=0;try{var m=d(e,g);if(!Aa||0!==m){if(!Aa&&(Ja=!0,f.onExit))f.onExit(m);ea(m,new sa(m))}}catch(n){n instanceof sa||("unwind"==n?Aa=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),k("exception thrown: "+c),ea(1,n)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),$a.unshift(c);Va($a)}}a=a||ca;if(!(0<cb)){if(f.preRun)for("function"==
typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)bb();Va(Wa);0<cb||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=wf;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var xf=!0;f.noInitialRun&&(xf=!1);Aa=!0;wf();
